# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='/static/img')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(upload_to='/static/img'),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ManyToManyField(to='core.Photo'),
        ),
    ]
