# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170102_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='core.Photo'),
        ),
    ]
