# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 18:38
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170102_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='short_info',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='detail',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='interest',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
